/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as InspecaoRouteImport } from './routes/inspecao'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroIdRouteImport } from './routes/cadastro.$id'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoRoute = InspecaoRouteImport.update({
  id: '/inspecao',
  path: '/inspecao',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroIdRoute = CadastroIdRouteImport.update({
  id: '/cadastro/$id',
  path: '/cadastro/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/inspecao': typeof InspecaoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/cadastro/$id': typeof CadastroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/inspecao': typeof InspecaoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/cadastro/$id': typeof CadastroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/inspecao': typeof InspecaoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/cadastro/$id': typeof CadastroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/empresas'
    | '/inspecao'
    | '/inventario'
    | '/login'
    | '/relatorios'
    | '/cadastro/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/empresas'
    | '/inspecao'
    | '/inventario'
    | '/login'
    | '/relatorios'
    | '/cadastro/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/empresas'
    | '/inspecao'
    | '/inventario'
    | '/login'
    | '/relatorios'
    | '/cadastro/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmpresasRoute: typeof EmpresasRoute
  InspecaoRoute: typeof InspecaoRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  CadastroIdRoute: typeof CadastroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao': {
      id: '/inspecao'
      path: '/inspecao'
      fullPath: '/inspecao'
      preLoaderRoute: typeof InspecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/$id': {
      id: '/cadastro/$id'
      path: '/cadastro/$id'
      fullPath: '/cadastro/$id'
      preLoaderRoute: typeof CadastroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmpresasRoute: EmpresasRoute,
  InspecaoRoute: InspecaoRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  CadastroIdRoute: CadastroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
