/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as InspecaoRouteImport } from './routes/inspecao'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroIdRouteImport } from './routes/cadastro.$id'

const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoRoute = InspecaoRouteImport.update({
  id: '/inspecao',
  path: '/inspecao',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroIdRoute = CadastroIdRouteImport.update({
  id: '/cadastro/$id',
  path: '/cadastro/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/equipe': typeof EquipeRoute
  '/inspecao': typeof InspecaoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/scanner': typeof ScannerRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/cadastro/$id': typeof CadastroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/equipe': typeof EquipeRoute
  '/inspecao': typeof InspecaoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/scanner': typeof ScannerRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/cadastro/$id': typeof CadastroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/equipe': typeof EquipeRoute
  '/inspecao': typeof InspecaoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/scanner': typeof ScannerRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/cadastro/$id': typeof CadastroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/equipe'
    | '/inspecao'
    | '/inventario'
    | '/login'
    | '/relatorios'
    | '/scanner'
    | '/solicitacoes'
    | '/cadastro/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/equipe'
    | '/inspecao'
    | '/inventario'
    | '/login'
    | '/relatorios'
    | '/scanner'
    | '/solicitacoes'
    | '/cadastro/$id'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/equipe'
    | '/inspecao'
    | '/inventario'
    | '/login'
    | '/relatorios'
    | '/scanner'
    | '/solicitacoes'
    | '/cadastro/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EmpresasRoute: typeof EmpresasRoute
  EquipeRoute: typeof EquipeRoute
  InspecaoRoute: typeof InspecaoRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ScannerRoute: typeof ScannerRoute
  SolicitacoesRoute: typeof SolicitacoesRoute
  CadastroIdRoute: typeof CadastroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao': {
      id: '/inspecao'
      path: '/inspecao'
      fullPath: '/inspecao'
      preLoaderRoute: typeof InspecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/$id': {
      id: '/cadastro/$id'
      path: '/cadastro/$id'
      fullPath: '/cadastro/$id'
      preLoaderRoute: typeof CadastroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EmpresasRoute: EmpresasRoute,
  EquipeRoute: EquipeRoute,
  InspecaoRoute: InspecaoRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  ScannerRoute: ScannerRoute,
  SolicitacoesRoute: SolicitacoesRoute,
  CadastroIdRoute: CadastroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
